namespace Gerador_de_Deck.Classes
{
    public static class CartasDescricao
    {
        public static string[] Descricao = {
            "Nenhuma Carta selecionada",
            "Evoca Esqueletos, lança raios terríveis e tem olhos rosa incandescentes que infelizmente não disparam raios laser.",
            "Gera um exército de Esqueletos. Encontre Tico e seus amigos Teco, Taco, Toco, Tuco, Jorge e cia.",
            "Tropa voadora que causa dano em área. Bebês Dragões nascem fofos, com fome e prontos para o churrasco.",
            "Não se engane com a carinha do pequeno pônei. Quando o Príncipe começar a correr, você será atropelado. Causa o dobro de dano ao atacar correndo.",
            "Lento, mas durão, só ataca construções. É um trator sobre duas pernas!",
            "Não se deixe enganar por seu cabelo cuidadosamente penteado: a Mosqueteira é uma atiradora infalível.",
            "A arena é comprovadamente uma zona sem borboletas. Nenhuma distração para Mini P.E.K.K.A, só destruição.",
            "Eeeee... Bola de Fogo! Incinera uma pequena área, causando muito dano. Dano reduzido às torres da coroa.",
            "Um resistente lutador de corpo a corpo. O primo bonito e culto do Bárbaro. Dizem que foi nomeado cavaleiro por causa do bigode impressionante.",
            "Um par de atacantes a distância, de armadura leve. Elas ajudam na batalha contra as unidades terrestres e aéreas, mas não contam o segredo de seus cabelos impecáveis.",
            "Um Esqueleto pequeno, levemente protegido, que lança bombas. Causa dano em área que pode eliminar um bando de inimigos.",
            "As Flechas atingem uma área extensa, danificando todos os inimigos. Dano reduzido às torres da coroa.",
            "Gera três Goblins em qualquer lugar da Arena. Cara, isso vai ser uma viagem!",
            "Raios atingem até três tropas ou construções inimigas com o maior número de pontos de vida na área de efeito. Dano reduzido às torres da coroa.",
            "Lutadora de corpo a corpo resistente, causa danos na área em sua volta. Bando ou horda, não importa! Ela só precisa de alguns giros para destruir o inimigo!",
            "Construção que gera Goblins Lanceiros. Mas não olhe lá dentro: você não quer saber como são feitos.",
            "Três atacantes de corpo a corpo rápidos, sem armaduras. Pequenos, rápidos, verdes e malvados!",
            "Três atacantes a distância sem armadura. Quem teve a ideia de ensinar os caras a atirar lanças? Quem achou que isso daria certo?",
            "Por mais bonitos que sejam, você não vai querer ver estes balões aparecendo no horizonte. Eles lançam bombas potentes e, quando derrubados, causam dano em área.",
            "Quanto maior o esqueleto, maior a bomba. Traz uma bomba que explode quando o Esqueleto Gigante morre.",
            "Construção defensiva que aloja um Bombardeiro. Causa dano em área e qualquer coisa tola o suficiente para ficar perto dele.",
            "Construção que mobiliza Esqueletos periodicamente para lutar contra o inimigo. Ao ser destruída, gera 4 Esqueletos. Sinistro!",
            "É um pássaro? É um avião? Não, são três atacantes voadores rápidos, sem armaduras, que vão acabar com você!",
            "Três lutadores de corpo a corpo fracos, porém muito velozes. Enterre seus inimigos nesta pilha de ossos!",
            "Que bela torre você tem! Seria uma pena se esta X-Besta acabasse com ela flecha por flecha, do outro lado da arena...",
            "Aumenta a velocidade de movimento e de ataque das tropas. Também faz construções atacar e evocar tropas mais rápido. Atacaaaar!",
            "Construção que mobiliza Bárbaros periodicamente, enviando-os para a luta contra o inimigo. Hora de fazer Bárbaros!",
            "Causa dano severo em uma área pequena e de forma bem impressionante! Dano reduzido às torres da coroa.",
            "Uma horda de atacantes de corpo a corpo com bigodes terríveis e um temperamento ainda pior.",
            "Construção defensiva. Atira balas de canhão de efeito letal, mas não pode atingir tropas voadoras.",
            "O Lava Hound é uma majestosa fera voadora que ataca construções. Os Lava Pups são bebês irritados e deselegantes que atacam tudo pela frente.",
            "Dispara um raio de fogo concentrado com dano que aumenta com o tempo. Usa um capacete porque voar tem seus perigos.",
            "Uma lutadora de corpo a corpo, com armadura pesada e lenta. Um pouco desequilibrada, mas com um soco de impacto.",
            "Congela tropas e construções, tornando-as incapazes de se mover ou de atacar. Todo mundo fica frio.",
            "Tropa rápida de corpo a corpo que alveja construções e pode pular sobre o rio. Veio para a batalha atendendo ao chamado de outro \"Corredor\".",
            "Construção defensiva, cozinha seus alvos e causa danos que aumentam com o tempo. Queima até os maiores e mais resistentes inimigos!",
            "Seis atacantes voadores rápidos, sem armadura. Três é demais, seis é uma horda!",
            "Construção defensiva. Quando o Eletruque não estiver aterrorizando o inimigo, sua energia é que deve ser aterrada.",
            "Lança gelo para diminuir a velocidade de movimento e de ataque dos inimigos. A personaliddade é gélida, mas o charme do bigode é \"caliente\"!",
            "Surpresa! É festa! Festa de Esqueletos, em qualquer lugar da arena! Oba!",
            "Reproduz a última Carta jogada por +1 unidade de Elixir.",
            "Cobre a área com uma toxina mortal, danificando tropas e construções inimigas. Mas deixa a grama verdinha e saudável. Vai entender...",
            "O homem mais impressionante que já pisou na arena, o Mago deixará todos boquiabertos com a sua beleza, ... e/ou Bolas de Fogo.",
            "A Fornalha gera dois Espíritos de Fogo ao mesmo tempo. Também faz umas panquecas divinas.",
            "Esses três Espíritos de Fogo estão em uma missão kamikaze para dar um abraço quentinho em você. Seria uma delícia se eles não estivessem pegando fogo.",
            "Eletrocuta e atordoa os inimigos, causando dano em uma área pequena. Dano reduzido às torres da coroa.",
            "O Mineiro consegue passar por debaixo da terra e aparecer em qualquer lugar da arena. Não é mágica. Chama-se pá!",
            "Sparky carrega lentamente, depois causa um dano TREMENDO em área. Sobrecarga é apelido.",
            "Uma garrafa de Fúria se quebrou e transformou um tronco inocente em... \"O Tronco\"! Agora, ele busca a vingança destruindo tudo pelo caminho.",
            "Lento, porém resistente. Só ataca construções. Ao ser destruído, explode causando dano em área e dividindo-se em dois Golemitas!",
            "Arrasta as tropas inimigas para o seu olho, causando dano ao longo do tempo, como um ímã: um tornado gigante que pensa que é um ímã. Não afeta construções.",
            "Dois Bárbaros com um tronco gigante correm para a construção mais próxima e causam danos significativos ao chegar lá, depois partem pra briga com espadas!",
            "É preciso gastar Elixir para produzir Elixir.",
            "É uma festa de Esqueletos no céu até que todos os balões sejam estourados... Aí vira uma festa de esqueletos no chão!",
            "Construção de defesa de longo alcance. Lança pedregulhos explosivos que causam dano em área. Não pode atingir alvos que chegam muito perto!",
            "Esta bela Princesa lança Flechas flamejantes de longe. Se ela aquece o seu coração, pode ser que você pegou fogo.",
            "Ele cai com um \"POW\", atordoa os inimigos que estiverem por perto e lança relâmpagos com as duas mãos. Que exibido!",
            "Três irmãos esqueléticos e destemidos com escudos. Derrube os escudos e só sobrarão três irmãos esqueléticos e destemidos.",
            "O Príncipe das Trevas causa dano em área e deixa seu inimigo espinhento resolver tudo, porque, quando ele fala, parece ter um balde na cabeça.",
            "Um trio de mulheres poderosas e independentes que lutam por justiça e honra. Desrespeitá-las não seria somente um erro, como também um verdadeiro pecado.",
            "Voa, tem armadura e grande poder. Sua única fraqueza são bolinhos.",
            "Destruir construções inimigas com um canhão enorme é seu trabalho. Cuidar da sua barba loura é sua paixão.",
            "Gera dois Bárbaros turbinados. São como os Bárbaros normais, só que mais fortes, melhores e mais rápidos.",
            "Ele corta árvores de dia e caça O Tronco à noite. Sua garrafa de Fúria vaza por todos os lados quando ele morre.",
            "Ela invoca morcegos para tomarem a dianteira, mesmo após a morte! Se você chegar muito perto, ela mostrará quem manda na parada.",
            "Este grandalhão azul gosta das coisas boas da vida: drinques com Elixir negro e atirar pedras. Suas pedras enormes passam por cima do alvo, acertando tudo que estiver atrás!",
            "Duplica todas as tropas aliadas na área de alvo. As tropas clonadas são vulneráveis, mas têm a mesma força da original. Não afeta construções.",
            "Durão, mira em construções e explode quando é destruído, atrasando inimigos próximos. Feito de gelo. Será? Sim.",
            "Gera um pequeno Espírito de Gelo para congelar um grupo de inimigos. Fique frio!",
            "Gera cinco criaturinhas voadoras e orelhudas. Mas não é por que elas têm orelhas grandes que são boas ouvintes.",
            "A Bandida corre para o alvo e começa um ataque poderoso! Enquanto ela corre, ninguém pode tocá-la. A máscara protege sua identidade... e dá uns pontinhos extras a ela!",
            "Ele causa MUITO dano ao se aproximar do alvo, mas já não podemos dizer o mesmo a longo alcance. As sobrancelhas charmosas compensam a falta de precisão.",
            "Ele lança seu machado como um bumerangue, atingindo todos os inimigos no caminho de ida e de volta. É um milagre ele não perder um braço.",
            "Corre muito, atira longe e masca chiclete. Como ele lança dardos com a boca cheia de chiclete? Anos de prática!",
            "O mestre construtor enviou sua primeira engenhoca para a arena! É uma máquina voadora veloz e divertida, porém frágil.",
            "Gera cinco Goblins, três com facas e dois com lanças, por um custo mais baixo de elixir. É um pacote especial de Goblins!",
            "Ele paira invisivelmente pela arena até se assustar com algum inimigo... E, então, ele ataca! Depois fica invisível de novo. Zzzz...",
            "Ele chega com a força de mil bigodes, depois pula de inimigo em inimigo causando grande dano em área. Saia da frente!",
            "Um canhão de rodinhas! Quem podia imaginar? Depois que você quebra o escudo, ele vira um canhão mortal.",
            "Ele rola, levanta e causa danos a tudo o que estiver pelo caminho. Depois se quebra e surge um Bárbaro. Como isso é possível?",
            "Cure suas tropas para que continuem lutando. As tropas aliadas são curadas enquanto estiverem dentro do alcance do feitiço. Construções não são afetadas.",
            "Não é nem um Mago, nem uma Arqueira. Ele atira com uma flecha mágica que passa danificando tudo pelo caminho. Não é tecnologia, é feitiçaria!",
            "Gera máquinas adoravelmente mortais que dão choque. Quem está por trás disso? Só o mestre construtor tem a resposta."
        };

        public static string[] Dica = { "Clique com o botão direito do mouse nos formulários para ver mais opções", "Selecione sua Arena, Raridade e Tipo de Carta de preferência, em Gerador de Deck",
                "Há mais de 39.443.226.966 possibilidades de Decks diferentes", "Remova as Cartas que você não possui do ciclo de geração, em Seleção de Cartas",
                "Salve seus Decks favoritos (Max: 50 Decks)", "Verifique atualizações periodicamente, em Atualizador", "Copie e cole Decks no dentro e fora do Programa",
                "Embaralhe seus Decks no Gerador, clicando com o botão direito do mouse", "Clique no baú ao lado das dicas para ver os melhores Decks atualmente (M.E.T.A)",
                "Visite meu canal no YouTube, clicando no ícone do YouTube", "Clique em Buscar Deck para gerar Decks até encontrar com o Elixir médio escolhido",
                "Clique em Configurações, para mudar algumas preferências de acordo com sua vontade", "Clique em Decks salvos para ver seu histórico de Decks",
                "Clique com o botão direito do mouse em cima da Carta para ver mais opções", "Monte seu Deck trocando Carta por Carta no Gerador, clicando com o botão direito do mouse na Carta",
                "Programa de código aberto, para estudos da lógica e algoritmos", "Clique no ícone do GitHub, em Sobre, para ver o código fonte do programa",
                "Envie dicas, críticas e bugs para o e-mail do desenvolvedor, em Sobre", "Ative a opção Gerador de Deck Inteligente para Gerar Decks melhores",
                "Clique em Ligar Gerador para gerar Cartas sem parar, até desligar", "O Gerador de Deck Inteligente não depende da Arena, Raridade e Tipo escolhido",
                "Desative/Ative a função Voltar ao Deck anterior, em Configurações", "Não é necessário Salvar nas Configurações, desmarcando/marcando já troca as funções. Mas é necessário salvar, caso queira que elas permaneçam",
                "Baixe outras Versões do Gerador de Deck, em Atualizador", "Alterne entre os temas Claro, Escuro e Padrão, em Configurações", "Alterne entre os modos Minimalismo/Gráfico dos Decks salvos, em Configurações",
                "Clique em Melhores Decks, para ver os Melhores Decks de todas as arenas atualmente",
                "Clique em Balanceamento, para ver as informações do último Balanceamento feito no Clash Royale" };

        public static string[] Atalhos = {
            "Pressione e segure G para Gerar Decks sem parar, em Gerador de Deck", "Pressione e segure E para Embaralhar o Deck sem parar, em Gerador de Deck", "Pressione Ctrl + C para Copiar o Deck, em Gerador de Deck",
            "Pressione Ctrl + V para Colar o Deck, em Gerador de Deck", "Pressione Ctrl + S para Salvar o Deck, em Gerador de Deck", "Pressione Ctrl + L para Limpar o Deck, em Gerador de Deck", "Pressione P em Seleção de Cartas para focar na caixa de pesquisa",
        };
    }
}
